### ISSUE TITLE
Parameter confusion in `EpiTraceAge_Convergence`

### ISSUE THREAD

**Issue by ChenWeiyan** [MagpiePKU/EpiTrace#10]
Hi Yi,

Thanks for the tool!

It seems in the function **EpiTraceAge_Convergence**, there is a parameter confusion with `ref_genome = "hg19", non_standard_clock = T` on **line-663**, where you internally call function **EpiTrace_prepare_object**.

Such parameter setting makes it impossible to set the reference genome outside of **EpiTraceAge_Convergence**, which will always lead to "hg19".

Please let me know if I missed something or my interpretation is wrong.

Best,
Weiyan

**Comment by MagpiePKU** [comment]
Hi Weiyan, this is related to issue #9 . The message is not useful (the code was originally written for human-only analysis). We removed the message in the @dev branch and you can install it via pak. Otherwise, you can ignore it. 

We would merge the branches to master hopefully within this week...
