### ISSUE TITLE
longer object length is not a multiple of shorter object length

### ISSUE THREAD

**Issue by KaiLi-2324** [MagpiePKU/EpiTrace#11]
Hi, @MagpiePKU . Thanks for developing EpiTrace. I had the warning "longer object length is not a multiple of shorter object length" when I was running EpiTraceAge_Convergence function, and the function ended after one iteration. Is this result expected? Thanks very much! The screenshot is shown below
![image](https://github.com/user-attachments/assets/c3dacc61-4c7a-4bb0-9dcb-0274fe72dd6b)

**Comment by MagpiePKU** [comment]
Hi @KaiLi-2324 , can you share a bit of the source data? It seems like that there's some cells got NA as age then the iteration stopped. This is possible but only after one round iteration may not be very normal.

**Comment by KaiLi-2324** [comment]
Hi, @MagpiePKU . Thanks for the prompt reply. I removed more low quality cells by incresing the minFrags parameter in ArchR, and EpiTraceAge_Convergence seems to work now. Thanks for your help.
![image](https://github.com/user-attachments/assets/621e2919-7151-4142-b5f1-961b8cb92305)

**Comment by MagpiePKU** [comment]
Good to know that. I am closing it now.
