### ISSUE TITLE
Figure 6 Reproducibility

### ISSUE THREAD

**Issue by RandyHsj** [MagpiePKU/EpiTrace#4]
While trying to coplot the RNAvelocity and Epitrace_Age like figure.6, I always encounter the problem of package conflict. I just want to ask what's the running environments of the Figure 6's codes to better fit the packages. I can show you some common conflicts as below:
1. ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scanpy 1.10.2 requires numpy<2,>=1.23, but you have numpy 2.0.0 which is incompatible.
scipy 1.11.4 requires numpy<1.28.0,>=1.21.6, but you have numpy 2.0.0 which is incompatible.
2. ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
petsc4py 3.21.3 requires numpy<3,>=2, but you have numpy 1.26.4 which is incompatible.
These codes are run under the environment of RNAvelocity(conda create -n RNAvelocity python=3.11, https://github.com/HubINEM/RNAvelocity)

**Comment by wjindaniorerio** [comment]
Hi, RandyHsj. I reproduced Figure 6 using Python 3.7. The detailed versions of the packages in the environment are listed in the attached file. 
[scvelo_env.txt](https://github.com/user-attachments/files/16280936/scvelo_env.txt)

**Comment by RandyHsj** [comment]
Thanks a lot for the info!

Best regards,
Shijie

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MagpiePKU** [comment]
Close for now.
