### ISSUE TITLE
Decouple large datasets from software

### ISSUE THREAD

**Issue by mfansler** [MagpiePKU/EpiTrace#6]
This package includes some large example datasets that do not appear essential for using the package. Could these be moved out of the package code to somewhere else?

For example, you could host the datasets on Figshare and instead provide code for users interested in a tutorial to download them.

**Comment by MagpiePKU** [comment]
Thanks for the suggestion. We plan to move some of the rds files into Figshare/Zenodo and only include the clock_gr_list (as this would be actively used -- it would include the G4 regions as well). Would make it in next update.
